#!/bin/sh -

# derby=/usr/share/java/derby.jar
derby=/opt/homebrew/opt/derby/libexec/lib/derbytools.jar
mypath=/Users/guilhermekameoka/Desktop/mydir/JDBCTutorial
mypackage=com/oracle/tutorial/jdbc

postgres=/Users/guilhermekameoka/Desktop/mydir/JDBCTutorial/BD2-14-postgresql-42.2.4.jar

if [ -r $mypath/src/$mypackage/$1.java -a -r $mypath/$2 ]
then
    javac -cp "$derby:$mypath/classes:$mypath/lib/JDBCTutorial.jar:$postgres" $mypath/src/$mypackage/$1.java

    if [ -r $mypath/src/$mypackage/$1.class ]
    then
        mv $mypath/src/$mypackage/$1.class $mypath/classes/$mypackage/

        java -cp "$derby:$mypath/classes:$postgres" $mypackage/$1 $mypath/$2
    fi
else 
    echo Missing file, check:
    ls $mypath/src/$mypackage/$1.java
    ls $mypath/$2
fi